name: Build PlatformIO Firmware

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install PlatformIO Core
        run: pip install -U platformio

      - name: Build the project
        run: pio run

      - name: Upload firmware artifact
        uses: actions/upload-artifact@v4
        with:
          name: mi-monitor-light-firmware-pio
          # 修正了这里的路径，将 esp32dev 替换为 lolin32_lite
          path: .pio/build/lolin32_lite/firmware.bin
